name: Build

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        build_type: [Debug, Release]
    runs-on: self-hosted
    env:
      CONAN_USER_HOME: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.10.5

      - name: Set up conan
        run: |
          pip install --user conan==2.3.2
          conan profile detect
          conan config install conan

      - name: Create package
        run: |
          $package_name=$(conan inspect . --format json -vquiet | ConvertFrom-Json).name
          $version = "0.0.$env:GITHUB_RUN_NUMBER"
          conan create . `
            -pr:h dev-msvc `
            -pr:b default `
            -s build_type=${{ matrix.build_type }} `
            --build=missing `
            --build=$package_name `
            --version=$version;
